### ISSUE TITLE
wrong flags used to compile C++ files

### ISSUE THREAD

**Issue by bastistician** [acanth-is/alcyon#4]
This should use `ALL_CXXFLAGS` rather than `ALL_OBJCXXFLAGS`:

https://github.com/spatialnous/alcyon/blob/496da21d98a0b06ab8b6ef13017bfdfad3339bfb/src/Makevars.in#L52

**Comment by pklampros** [comment]
Fixed, thanks!

**Comment by bastistician** [comment]
Any plans to release the fixed version? Currently the package fails to install for me on Alpine Linux because of this bug. Thanks!

**Comment by pklampros** [comment]
Do you mean on CRAN?
I updated it here, but CRAN is not happy with constant updates (and there was one in August) - so just holding on. Since it's causing issues maybe it is time to cut a new version

**Comment by bastistician** [comment]
Yes, that would be helpful and is certainly in line with the policy ("no more than every 1--2 months").

**Comment by bastistician** [comment]
> Since it's causing issues maybe it is time to cut a new version

Yes, please. :)
Note that CRAN will close submissions for two weeks starting from Monday.

**Comment by pklampros** [comment]
Ah, let me try to get t his sorted today then... Here's hoping I don't get any ASAN issues when I upload :crossed_fingers:

**Comment by pklampros** [comment]
New version 0.6.0 made its way to cran, see here for status of each platform: https://cran.r-project.org/web/checks/check_results_alcyon.html

**Comment by bastistician** [comment]
Thanks! Installation was successful on my Alpine Linux machine.
